# must add version here, if not, then there will be an error: unsupported config


version: "3"

services:
  db:
    image: "mysql:latest"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d"
  server:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
