// Code generated by protoc-gen-go. DO NOT EDIT.
// source: student.proto

package student

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Student struct {
	Id                   *int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	IdCard               *IDCard  `protobuf:"bytes,3,opt,name=idCard" json:"idCard,omitempty"`
	Books                []*Book  `protobuf:"bytes,4,rep,name=books" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{0}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Student) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Student) GetIdCard() *IDCard {
	if m != nil {
		return m.IdCard
	}
	return nil
}

func (m *Student) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type IDCard struct {
	Id                   *int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDCard) Reset()         { *m = IDCard{} }
func (m *IDCard) String() string { return proto.CompactTextString(m) }
func (*IDCard) ProtoMessage()    {}
func (*IDCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{1}
}

func (m *IDCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDCard.Unmarshal(m, b)
}
func (m *IDCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDCard.Marshal(b, m, deterministic)
}
func (m *IDCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDCard.Merge(m, src)
}
func (m *IDCard) XXX_Size() int {
	return xxx_messageInfo_IDCard.Size(m)
}
func (m *IDCard) XXX_DiscardUnknown() {
	xxx_messageInfo_IDCard.DiscardUnknown(m)
}

var xxx_messageInfo_IDCard proto.InternalMessageInfo

func (m *IDCard) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type Book struct {
	Id                   *int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{2}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Book) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Student)(nil), "student.Student")
	proto.RegisterType((*IDCard)(nil), "student.IDCard")
	proto.RegisterType((*Book)(nil), "student.Book")
}

func init() { proto.RegisterFile("student.proto", fileDescriptor_94a1c1b032ad0c00) }

var fileDescriptor_94a1c1b032ad0c00 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2e, 0x29, 0x4d,
	0x49, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xaa, 0xb9,
	0xd8, 0x83, 0x21, 0x4c, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6,
	0x20, 0xa6, 0xcc, 0x14, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x30, 0x5b, 0x48, 0x9d, 0x8b, 0x2d, 0x33, 0xc5, 0x39, 0xb1, 0x28, 0x45, 0x82,
	0x59, 0x81, 0x51, 0x83, 0xdb, 0x88, 0x5f, 0x0f, 0x66, 0xae, 0xa7, 0x0b, 0x48, 0x38, 0x08, 0x2a,
	0x2d, 0xa4, 0xcc, 0xc5, 0x9a, 0x94, 0x9f, 0x9f, 0x5d, 0x2c, 0xc1, 0xa2, 0xc0, 0xac, 0xc1, 0x6d,
	0xc4, 0x0b, 0x57, 0xe7, 0x94, 0x9f, 0x9f, 0x1d, 0x04, 0x91, 0x53, 0x92, 0xe0, 0x62, 0x83, 0x68,
	0x43, 0xb7, 0x5b, 0x49, 0x8b, 0x8b, 0x05, 0xa4, 0x90, 0x18, 0x37, 0x01, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xbd, 0x9f, 0xc1, 0xb3, 0xdb, 0x00, 0x00, 0x00,
}
